In [1]:
# %pip install pandas==2.2.3

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Bạn hãy dùng Pandas đọc file dữ liệu All_player_stats và tìm các thông tin sau:
# Câu 1: Thông tin tổng quan về bộ dữ liệu này
# Câu 2: Sắp xếp dataframe theo thứ tự tăng dần/giảm dần số bàn thắng
# Câu 3: Hãy tìm ra cầu thủ nào bị nhiều thẻ vàng nhất, nhiều thẻ đỏ nhất, thi đấu nhiều nhất
# Câu 4: Hãy tìm ra cầu thủ thi đấu nhiều nhất của từng CLB
# Câu 5: Hãy tìm ra cầu thủ ghi nhiều bàn thắng nhất, với vị trí Defender

In [4]:
# Đọc dữ liệu từ file csv
df = pd.read_csv('all_players_stats.csv')
df

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
0,Arsenal,7,Bukayo Saka,Defender/Midfielder,40,3,12,2,6.0,0.0
1,Arsenal,6,Gabriel,Defender,37,1,5,0,7.0,1.0
2,Arsenal,32,Aaron Ramsdale,Goalkeeper,37,0,0,0,1.0,0.0
3,Arsenal,4,Ben White,Defender,37,0,0,0,3.0,0.0
4,Arsenal,8,Martin Odegaard,Midfielder,36,4,7,0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...
618,Wolverhampton Wanderers,21,John Ruddy,Goalkeeper,5,1,0,0,0.0,0.0
619,Wolverhampton Wanderers,27,Romain Saïss,Defender/Midfielder,32,0,3,0,6.0,0.0
620,Wolverhampton Wanderers,24,Tote Gomes,Defender,5,0,0,0,1.0,0.0
621,Wolverhampton Wanderers,37,Adama Traoré,Midfielder/Forward,11,12,1,0,0.0,0.0
622,Wolverhampton Wanderers,11,Trincão,Midfielder/Forward,16,14,3,0,0.0,0.0

In [5]:
# Câu 1: Thông tin tổng quan về bộ dữ liệu này

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Team           623 non-null    object
 1   JerseyNo       623 non-null    int64
 2   Player         623 non-null    object
 3   Position       623 non-null    object
 4   Apearances     623 non-null    int64
 5   Substitutions  623 non-null    int64
 6   Goals          623 non-null    int64
 7   Penalties      623 non-null    int64
 8   YellowCards    623 non-null    float64
 9   RedCards       623 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 48.8+ KB

In [7]:
df.describe()

,JerseyNo,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
count,623.000000,623.000000,623.000000,623.000000,623.000000,623.000000,623.000000
mean,22.597111,16.861958,4.630819,2.245586,0.168539,2.457464,0.086677
std,18.719450,13.950425,4.950411,4.072776,0.787057,2.694708,0.303568
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,18.000000,16.000000,3.000000,1.000000,0.000000,2.000000,0.000000
75%,30.000000,27.500000,7.000000,3.000000,0.000000,4.000000,0.000000
max,97.000000,54.000000,25.000000,31.000000,9.000000,12.000000,2.000000

In [8]:
# Câu 2: Sắp xếp dataframe theo thứ tự tăng dần/giảm dần số bàn thắng

In [9]:
sorted_df = df.sort_values(by='Goals', ascending=False)
sorted_df

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
341,Liverpool,11,Mohamed Salah,Midfielder/Forward,44,6,31,6,1.0,0.0
514,Tottenham Hotspur,10,Harry Kane,Forward,47,3,27,4,5.0,0.0
407,Manchester United,7,Cristiano Ronaldo,Midfielder/Forward,35,3,24,3,9.0,0.0
511,Tottenham Hotspur,7,SON Heung-min,Midfielder/Forward,39,6,24,0,3.0,0.0
367,Manchester City,26,Riyad Mahrez,Midfielder/Forward,31,16,24,7,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
87,Brentford,28,Mads Bidstrup,Midfielder,3,5,0,0,0.0,0.0
88,Brentford,49,Jonas Lössl,Goalkeeper,3,0,0,0,0.0,0.0
336,Liverpool,77,James Norris,Defender/Midfielder,0,1,0,0,0.0,0.0
335,Liverpool,80,Tyler Morton,Midfielder,6,3,0,0,2.0,0.0
389,Manchester United,75,Alejandro Garnacho,Midfielder/Forward,0,2,0,0,0.0,0.0

In [10]:
sorted_df = df.sort_values(by='Goals', ascending=True)
sorted_df

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
465,Norwich City,46,Jonathan Rowe,Midfielder/Forward,0,15,0,0,0.0,0.0
262,Leeds United,33,Leo Hjelde,Defender,1,2,0,0,0.0,0.0
261,Leeds United,17,Hélder Costa,Midfielder/Forward,1,1,0,0,0.0,0.0
533,Watford,8,Tom Cleverley,Midfielder,21,9,0,0,2.0,0.0
259,Leeds United,42,Sam Greenwood,Forward,2,7,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
511,Tottenham Hotspur,7,SON Heung-min,Midfielder/Forward,39,6,24,0,3.0,0.0
367,Manchester City,26,Riyad Mahrez,Midfielder/Forward,31,16,24,7,1.0,0.0
407,Manchester United,7,Cristiano Ronaldo,Midfielder/Forward,35,3,24,3,9.0,0.0
514,Tottenham Hotspur,10,Harry Kane,Forward,47,3,27,4,5.0,0.0
341,Liverpool,11,Mohamed Salah,Midfielder/Forward,44,6,31,6,1.0,0.0

In [11]:
# Câu 3: Hãy tìm ra cầu thủ nào bị nhiều thẻ vàng nhất, nhiều thẻ đỏ nhất, thi đấu nhiều nhất

# Apearances: Antonio Rüdiger - 54
# YellowCards: Conor Gallagher, James Tarkowski, Antonio Rüdiger - 12
# RedCards: Granit Xhaka, Aaron Cresswell, Raúl Jiménez, Ezri Konsa - 2

In [12]:
df[df.Apearances == np.max(df.Apearances)]

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
178,Chelsea,2,Antonio Rüdiger,Defender,54,0,5,0,12.0,0.0

In [13]:
df[df.YellowCards == np.max(df.YellowCards)]

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
149,Burnley,5,James Tarkowski,Defender,37,0,1,0,12.0,0.0
178,Chelsea,2,Antonio Rüdiger,Defender,54,0,5,0,12.0,0.0
197,Crystal Palace,23,Conor Gallagher,Midfielder,37,2,8,0,12.0,0.0

In [14]:
df[df.RedCards == np.max(df.RedCards)]

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards
5,Arsenal,34,Granit Xhaka,Defender/Midfielder,29,1,1,0,10.0,2.0
45,Aston Villa,4,Ezri Konsa,Defender/Midfielder,30,1,2,0,4.0,2.0
575,West Ham United,3,Aaron Cresswell,Defender,41,1,2,0,4.0,2.0
608,Wolverhampton Wanderers,9,Raúl Jiménez,Forward,30,6,6,1,5.0,2.0

In [15]:
# Câu 4: Hãy tìm ra cầu thủ thi đấu nhiều nhất của từng CLB

In [16]:
grouped_df = df.groupby('Team')
grouped_df

In [17]:
for team, group_df in grouped_df:
    print('\n\n', team)
    # print(group_df[group_df.Apearances == np.max(group_df.Apearances)])
    print(group_df.sort_values(by='Apearances', ascending=False).head(1))
    print(group_df.sort_values(by='Apearances', ascending=False).reset_index().loc[0])

    # break

 Arsenal
      Team  JerseyNo       Player             Position  Apearances  \
0  Arsenal         7  Bukayo Saka  Defender/Midfielder          40

   Substitutions  Goals  Penalties  YellowCards  RedCards
0              3     12          2          6.0       0.0
index                              0
Team                         Arsenal
JerseyNo                           7
Player                   Bukayo Saka
Position         Defender/Midfielder
Apearances                        40
Substitutions                      3
Goals                             12
Penalties                          2
YellowCards                      6.0
RedCards                         0.0
Name: 0, dtype: object


 Aston Villa
           Team  JerseyNo      Player             Position  Apearances  \
31  Aston Villa         2  Matty Cash  Defender/Midfielder          40

    Substitutions  Goals  Penalties  YellowCards  RedCards
31              0      4          0          8.0       0.0
index                             31
Team                     Aston Villa
JerseyNo                           2
Player                    Matty Cash
Position         Defender/Midfielder
Apearances                        40
Substitutions                      0
Goals                              4
Penalties                          0
YellowCards                      8.0
RedCards                         0.0
Name: 0, dtype: object


 Brentford
         Team  JerseyNo          Player  Position  Apearances  Substitutions  \
64  Brentford        18  Pontus Jansson  Defender          39              0

    Goals  Penalties  YellowCards  RedCards
64      3          0          7.0       0.0
index                        64
Team                  Brentford
JerseyNo                     18
Player           Pontus Jansson
Position               Defender
Apearances                   39
Substitutions                 0
Goals                         3
Penalties                     0
YellowCards                 7.0
RedCards                    0.0
Name: 0, dtype: object


 Brighton and Hove Albion
                         Team  JerseyNo          Player    Position  \
119  Brighton and Hove Albion         1  Robert Sánchez  Goalkeeper

     Apearances  Substitutions  Goals  Penalties  YellowCards  RedCards
119          38              0      0          0          3.0       1.0
index                                 119
Team             Brighton and Hove Albion
JerseyNo                                1
Player                     Robert Sánchez
Position                       Goalkeeper
Apearances                             38
Substitutions                           0
Goals                                   0
Penalties                               0
YellowCards                           3.0
RedCards                              1.0
Name: 0, dtype: object


 Burnley
        Team  JerseyNo     Player    Position  Apearances  Substitutions  \
145  Burnley         1  Nick Pope  Goalkeeper          39              0

     Goals  Penalties  YellowCards  RedCards
145      0          0          1.0       0.0
index                   145
Team                Burnley
JerseyNo                  1
Player            Nick Pope
Position         Goalkeeper
Apearances               39
Substitutions             0
Goals                     0
Penalties                 0
YellowCards             1.0
RedCards                0.0
Name: 0, dtype: object


 Chelsea
        Team  JerseyNo           Player  Position  Apearances  Substitutions  \
178  Chelsea         2  Antonio Rüdiger  Defender          54              0

     Goals  Penalties  YellowCards  RedCards
178      5          0         12.0       0.0
index                        178
Team                     Chelsea
JerseyNo                       2
Player           Antonio Rüdiger
Position                Defender
Apearances                    54
Substitutions                  0
Goals                          5
Penalties                      0
YellowCards                 12.0
RedCards                     0.0
Name: 0, dtype: object


 Crystal Palace
               Team  JerseyNo      Player  Position  Apearances  \
199  Crystal Palace         6  Marc Guehi  Defender          42

     Substitutions  Goals  Penalties  YellowCards  RedCards
199              0      4          0          4.0       0.0
index                       199
Team             Crystal Palace
JerseyNo                      6
Player               Marc Guehi
Position               Defender
Apearances                   42
Substitutions                 0
Goals                         4
Penalties                     0
YellowCards                 4.0
RedCards                    0.0
Name: 0, dtype: object


 Everton
        Team  JerseyNo           Player    Position  Apearances  \
242  Everton         1  Jordan Pickford  Goalkeeper          37

     Substitutions  Goals  Penalties  YellowCards  RedCards
242              0      0          0          2.0       0.0
index                        242
Team                     Everton
JerseyNo                       1
Player           Jordan Pickford
Position              Goalkeeper
Apearances                    37
Substitutions                  0
Goals                          0
Penalties                      0
YellowCards                  2.0
RedCards                     0.0
Name: 0, dtype: object


 Leeds United
             Team  JerseyNo         Player    Position  Apearances  \
271  Leeds United         1  Illan Meslier  Goalkeeper          42

     Substitutions  Goals  Penalties  YellowCards  RedCards
271              0      0          0          2.0       0.0
index                      271
Team              Leeds United
JerseyNo                     1
Player           Illan Meslier
Position            Goalkeeper
Apearances                  42
Substitutions                0
Goals                        0
Penalties                    0
YellowCards                2.0
RedCards                   0.0
Name: 0, dtype: object


 Leicester City
               Team  JerseyNo             Player    Position  Apearances  \
303  Leicester City         1  Kasper Schmeichel  Goalkeeper          53

     Substitutions  Goals  Penalties  YellowCards  RedCards
303              0      0          0          1.0       0.0
index                          303
Team                Leicester City
JerseyNo                         1
Player           Kasper Schmeichel
Position                Goalkeeper
Apearances                      53
Substitutions                    0
Goals                            0
Penalties                        0
YellowCards                    1.0
RedCards                       0.0
Name: 0, dtype: object


 Liverpool
          Team  JerseyNo          Player    Position  Apearances  \
312  Liverpool         1  Alisson Becker  Goalkeeper          53

     Substitutions  Goals  Penalties  YellowCards  RedCards
312              0      0          0          0.0       0.0
index                       312
Team                  Liverpool
JerseyNo                      1
Player           Alisson Becker
Position             Goalkeeper
Apearances                   53
Substitutions                 0
Goals                         0
Penalties                     0
YellowCards                 0.0
RedCards                    0.0
Name: 0, dtype: object


 Manchester City
                Team  JerseyNo        Player  Position  Apearances  \
362  Manchester City        27  João Cancelo  Defender          51

     Substitutions  Goals  Penalties  YellowCards  RedCards
362              1      3          0         10.0       0.0
index                        362
Team             Manchester City
JerseyNo                      27
Player              João Cancelo
Position                Defender
Apearances                    51
Substitutions                  1
Goals                          3
Penalties                      0
YellowCards                 10.0
RedCards                     0.0
Name: 0, dtype: object


 Manchester United
                  Team  JerseyNo        Player    Position  Apearances  \
384  Manchester United         1  David De Gea  Goalkeeper          46

     Substitutions  Goals  Penalties  YellowCards  RedCards
384              0      0          0          0.0       0.0
index                          384
Team             Manchester United
JerseyNo                         1
Player                David De Gea
Position                Goalkeeper
Apearances                      46
Substitutions                    0
Goals                            0
Penalties                        0
YellowCards                    0.0
RedCards                       0.0
Name: 0, dtype: object


 Newcastle United
                 Team  JerseyNo     Player            Position  Apearances  \
427  Newcastle United         7  Joelinton  Midfielder/Forward          32

     Substitutions  Goals  Penalties  YellowCards  RedCards
427              5      4          0          8.0       0.0
index                           427
Team               Newcastle United
JerseyNo                          7
Player                    Joelinton
Position         Midfielder/Forward
Apearances                       32
Substitutions                     5
Goals                             4
Penalties                         0
YellowCards                     8.0
RedCards                        0.0
Name: 0, dtype: object


 Norwich City
             Team  JerseyNo       Player Position  Apearances  Substitutions  \
463  Norwich City        22  Teemu Pukki  Forward          38              3

     Goals  Penalties  YellowCards  RedCards
463     11          3          5.0       0.0
index                     463
Team             Norwich City
JerseyNo                   22
Player            Teemu Pukki
Position              Forward
Apearances                 38
Substitutions               3
Goals                      11
Penalties                   3
YellowCards               5.0
RedCards                  0.0
Name: 0, dtype: object


 Southampton
            Team  JerseyNo             Player    Position  Apearances  \
499  Southampton         8  James Ward-Prowse  Midfielder          41

     Substitutions  Goals  Penalties  YellowCards  RedCards
499              1     11          5          3.0       1.0
index                          499
Team                   Southampton
JerseyNo                         8
Player           James Ward-Prowse
Position                Midfielder
Apearances                      41
Substitutions                    1
Goals                           11
Penalties                        5
YellowCards                    3.0
RedCards                       1.0
Name: 0, dtype: object


 Tottenham Hotspur
                  Team  JerseyNo      Player Position  Apearances  \
514  Tottenham Hotspur        10  Harry Kane  Forward          47

     Substitutions  Goals  Penalties  YellowCards  RedCards
514              3     27          4          5.0       0.0
index                          514
Team             Tottenham Hotspur
JerseyNo                        10
Player                  Harry Kane
Position                   Forward
Apearances                      47
Substitutions                    3
Goals                           27
Penalties                        4
YellowCards                    5.0
RedCards                       0.0
Name: 0, dtype: object


 Watford
        Team  JerseyNo          Player    Position  Apearances  Substitutions  \
563  Watford        19  Moussa Sissoko  Midfielder          37              1

     Goals  Penalties  YellowCards  RedCards
563      2          0          5.0       0.0
index                       563
Team                    Watford
JerseyNo                     19
Player           Moussa Sissoko
Position             Midfielder
Apearances                   37
Substitutions                 1
Goals                         2
Penalties                     0
YellowCards                 5.0
RedCards                    0.0
Name: 0, dtype: object


 West Ham United
                Team  JerseyNo       Player             Position  Apearances  \
590  West Ham United        41  Declan Rice  Defender/Midfielder          48

     Substitutions  Goals  Penalties  YellowCards  RedCards
590              2      5          0         11.0       0.0
index                            590
Team                 West Ham United
JerseyNo                          41
Player                   Declan Rice
Position         Defender/Midfielder
Apearances                        48
Substitutions                      2
Goals                              5
Penalties                          0
YellowCards                     11.0
RedCards                         0.0
Name: 0, dtype: object


 Wolverhampton Wanderers
                        Team  JerseyNo       Player             Position  \
600  Wolverhampton Wanderers        16  Conor Coady  Defender/Midfielder

     Apearances  Substitutions  Goals  Penalties  YellowCards  RedCards
600          41              1      4          0          4.0       0.0
index                                600
Team             Wolverhampton Wanderers
JerseyNo                              16
Player                       Conor Coady
Position             Defender/Midfielder
Apearances                            41
Substitutions                          1
Goals                                  4
Penalties                              0
YellowCards                          4.0
RedCards                             0.0
Name: 0, dtype: object

In [18]:
# Câu 5: Hãy tìm ra cầu thủ ghi nhiều bàn thắng nhất, với vị trí Defender

In [19]:
def check_defender(position):
    return 'Defender' in position

In [20]:
# Bước 1: Lọc ra vị trí Defender
df['check_defender'] = df['Position'].apply(check_defender)
df.loc[df.check_defender == True]

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards,check_defender
0,Arsenal,7,Bukayo Saka,Defender/Midfielder,40,3,12,2,6.0,0.0,True
1,Arsenal,6,Gabriel,Defender,37,1,5,0,7.0,1.0,True
3,Arsenal,4,Ben White,Defender,37,0,0,0,3.0,0.0,True
5,Arsenal,34,Granit Xhaka,Defender/Midfielder,29,1,1,0,10.0,2.0,True
9,Arsenal,3,Kieran Tierney,Defender/Midfielder,24,1,1,0,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...
613,Wolverhampton Wanderers,5,Marçal,Defender,18,1,0,0,3.0,0.0,True
614,Wolverhampton Wanderers,14,Yerson Mosquera,Defender,1,0,0,0,0.0,0.0,True
615,Wolverhampton Wanderers,22,Nélson Semedo,Defender,27,1,1,0,1.0,0.0,True
619,Wolverhampton Wanderers,27,Romain Saïss,Defender/Midfielder,32,0,3,0,6.0,0.0,True
620,Wolverhampton Wanderers,24,Tote Gomes,Defender,5,0,0,0,1.0,0.0,True

In [21]:
# Bước 2: Lấy ra cầu thủ ghi nhiều bàn thắng nhất
df.loc[df.check_defender == True].sort_values(by='Goals', ascending=False).head(1)

,Team,JerseyNo,Player,Position,Apearances,Substitutions,Goals,Penalties,YellowCards,RedCards,check_defender
0,Arsenal,7,Bukayo Saka,Defender/Midfielder,40,3,12,2,6.0,0.0,True